
branding = {
        "toolsName" : "XCP-ng XenServer Tools",
        "installerProductName" : "XCP-ng XenServer Tools Installer",
        "manufacturer" : "XCP-ng",
        "installerKeyWords" : "XCP-ng XenServer Windows Installer",
        "shortTools" : "XenTools",
        "installerServiceName" : "XCP-ng Xen Installer",
        "shortInstallerServiceName": "XenPVInstall",
        "installWizardName" : "XCP-ng Xen Install Wizard",
        "pvtoolsLong" : "XCP-ng Windows PV Tools",
        "pvTools" : "XCP-ng Xen PV Tools",
        "hypervisorAndOs" : "XCP-ng Xen Windows",
        "pvDrivers" : "PV Drivers",
        "driverKeyWords" : "XCP-ng Xen Drivers",
        "driverDescription" : "XCP-ng Xen Windows Drivers",
        "driverComments" : "Paravitualized Windows Drivers For XCP-ng",
        "pvDriversLong" : "XCP-ng PV Drivers for Windows",
        "hypervisor" : "Xen",
        "hypervisorProduct" : "XCP-ng",
        "guestAgentLong" : "XCP-ng XenServer Windows Guest Agent",
        "guestAgent" : "XCP-ng Xen Guest Agent",
        "guestServiceShort" : "XenSvc",
        "guestServiceDesc" : "Monitors and provides various metrics to XenStore",
        "vssLong" : "XCP-ng XenServer VSS Provider",
        "managementName" : "Windows Management Agent",
        "managementDesc" : "Installation and Update Agent",
        "installAgentShort" : "InstallAgent",
        "installAgentDesc" : "Installs and updates management agent",
        "installAgentRegKey" : R"SOFTWARE\\XCP-ng\\InstallAgent",
        "language" : "1033",
        "languages" : "1033",
        "manufacturerLong" : "XCP-ng",
        "toolsForVMs" : "XCP-ng Tools For Virtual Machines",
        "guestLibDesc" : "XCP-ng Xen Windows Guest Agent Support Library",
        "copyrightGuestLib" : "Copyright 2018 XCP-ng and Copyright 2012-2016 Citrix Systems, Inc.",
        "copyrightGuestAgent" : "Copyright 2018 XCP-ng and Copyright 2012-2016 Citrix Systems, Inc.",
        "copyrightXenDpriv" : "Copyright 2018 XCP-ng and Copyright 2012-2016 Citrix Systems, Inc.",
        "xenDprivDesc" : "XCP-ng XenServer Windows Deprivileged Client",

        "setComputerName" : "Set Computer Name",
        "errNoWMI" : "XCP-ng XenServer guest Agent cannotfix XenIface WMI interface",
        "GuestAgentLogName" : "XenGuestAgentLog",
        "GuestAgentLogSource" : "XenGuestAgent",
        "setupErr" : "XenServer Setup.exe error",
        "processFail" : "Failed to create process %s %x", #commandline #windows error code
        "setupHelp" : "Valid arguments are:\\n /TEST\\n/passive\\n/quiet\\n/norestart\\n/forcerestart",
        "noSystemDir" : "Unable to read system directory",
        "setupLogDir" : "XSToolSetup",
        "copyrightInstallAgent" : "Copyright 2018 XCP-ng and Copyright 2015-2016 Citrix Systems, Inc.",
        "copyrightBrandSupport" : "Copyright 2018 XCP-ng and Copyright 2016 Citrix Systems, Inc.",
        "copyrightHelperFunctions" : "Copyright 2018 XCP-ng and Copyright 2016 Citrix Systems, Inc.",
        "copyrightHardwareDevice" : "Copyright 2018 XCP-ng and Copyright 2016 Citrix Systems, Inc.",
        "copyrightPInvokeWrap" : "Copyright 2018 XCP-ng and Copyright 2016 Citrix Systems, Inc.",
        "copyrightPVDriversRemoval" : "Copyright 2018 XCP-ng and Copyright 2016 Citrix Systems, Inc.",
        "copyrightUninstall" : "Copyright 2018 XCP-ng and Copyright 2016 Citrix Systems, Inc.",
        "errMSINoMem":"Insufficient memory to allocate msiexec string",
        "errFilePathNoMem":"Insufficient memory to get file path",
        "errNoLogPath":"Can't get logging path",
        "errCmdLineNoMem":"Insufficient memory to allocate cmdline string",
        "errMSIInstallFail":"The MSI Install failed with exit code %d\\nSee %s for more details", #MSI exit code, #Log File Location
        "errDotNetNeeded":"Microsoft .Net Framework 3.5 or higher is required",
        "twoCharBrand":"XS",
        "updater" : "ManagementAgentUpdater",
        "copyrightUpdater" : "Copyright 2018 XCP-ng and Copyright 2016 Citrix Systems, Inc.",
        "updaterURL" : "",
        "updaterLong" : "XCP-ng Management Agent Auto-Updater",
        "updaterDesc" : "Automatically checks and updates XenServer tools",
        "laterVersion" : "A later version of Windows Management Agent is already installed.  Setup will now exit",
        "windowsRequired" : "This version of the XCP-ng Windows Management Agent requires Windows Vista, Windows Server 2008 or Later.  For Windows XP and 2003 try installing XenLegacy.exe",
        "evtServiceStarting" : "Service Starting",
        "evtException" : "Exception: ",
        "evtServiceStopping" : "Service Stopping",
        "evtStopLock" : "Service Stopping (locked)",
        "evtStopShutdown" : "Service Stopping (shutdown)",
        "evtStopNothing" : "Service Stopping (nothing running)",
        "evtStopJoin" : "Service Stopping (joining thread)",
        "evtStopped" : "Service Stopping (done)",
        "32BitNotOn64" : "Please install the 64 bit version of this package on 64 bit systems",
        "allowAutoUpdate" : "YES",
        "allowDriverUpdate" : "NO",
        "allowDriverInstall" : "YES",
        "installAndUpdateTitle" : "Installation and Update Settings",
        "installAndUpdateDesc" : "Click Next to accept recommended settings",
        "ioDesc" : "I/O drivers improve performance, functionality and reliability",
        "ioInstall" : "Install I/O Drivers Now",
        "mgmtDesc" : "The management agent automatically updates itself when new versions are available",
        "mgmtAllow" : "Allow automatic management agent updates",
        "mgmtDisallow" : "Disallow automatic management agent updates",
        "ioUpdDesc" : "The management agent can install I/O drivers when new versions are available",
        "ioUpdAllow" : "Allow automatic I/O driver updates by the management agent",
        "ioUpdDisallow" : "Disallow automatic I/O driver updates by the management agent",
        "updDisclaim" : "Automatic updates may be overridden by pool policies",
        "whqlWarn" : "Customers using Windows Update for I/O driver updates should not select this option",
        "userAgent" : "XCP-ng XenServer AutoUpdate",
        "anonymousUsage" : "Send anonymous usage information to Citrix",
        "setupString":"Setup",
        "installSuccess":"installed successfully",
        "installFailed":"failed to install",
        "notSupport":"not supported",
}

filenames = {
        "legacy" : "XenLegacy.Exe",
        "legacyuninstallerfix" : "xluninstallerfix.exe",
        "driversmsix86" : "XCp-ngXenDriversX86.msi",
        "driversmsix64" : "XCp-ngXenDriversX64.msi",
        "vssmsix86" : "XCp-ngVssX86.msi",
        "vssmsix64" : "XCp-ngVssX64.msi",
        "guestagentmsix86" : "XCp-ngGuestAgentX86.msi",
        "guestagentmsix64" : "XCp-ngGuestAgentX64.msi",
        "installwizard" : "InstallWizard.msi",
        "managementx64" : "managementagentx64.msi",
        "managementx86" : "managementagentx86.msi",
        "setup" : "setup.exe",
        "dpriv" : "XenDpriv.exe",
        "dprivcfg" : "XenDpriv.exe.config",
        "agent" : "XenGuestAgent.exe",
        "agentcfg" : "XenGuestAgent.exe.config",
        "installVSS" : "install-XenProvider.cmd",
        "uninstallVSS" : "uninstall-XenProvider.cmd",
}

filenames_in_msi_to_sign = [
    'BrandSupport\\brandsat.dll',
    'BrandSupport\\BrandSupport.dll',
    'installwizard\\netsettings\\Win32\\netsettings.exe',
    'installwizard\\netsettings\\x64\\netsettings.exe',
    'installwizard\\qnetsettings\\Win32\\qnetsettings.exe',
    'installwizard\\qnetsettings\\x64\\qnetsettings.exe',
    "xenguestagent\\xendpriv\\XenDPriv.exe",
    "xenguestagent\\xenupdater\\ManagementAgentUpdater.exe",
    "xenguestagent\\xenguestagent\\XenGuestLib.Dll" ,
    "xenguestagent\\xenguestagent\\Interop.NetFwTypeLib.dll", 
    "xenguestagent\\xenupdater\\Interop.TaskScheduler.dll",
    'xenvss\\x64\\xenvss.dll',
    'xenvss\\x86\\xenvss.dll',
    'xenvss\\x64\\vssclient.dll', 
    'xenvss\\x86\\vssclient.dll', 
    "xenguestagent\\xenguestagent\\xenguestagent.exe",
    "InstallAgent\\InstallAgent.exe",
    "Libraries\\PInvokeWrap.dll",
    "Libraries\\HelperFunctions.dll",
    "Libraries\\HardwareDevice.dll",
    "Libraries\\PVDriversRemoval.dll",
    "Uninstall\\Uninstall.exe",
]

resources = {
        "icon" : "xen.ico",
}

bitmaps = "..\\..\\src\\bitmaps"

languagecode = {
        "culture" : "enus",
        "language" : "0x09",
        "sublang" : "0x04",
}

cultures = {
        "default" : "en-us",
        "others" : [],
}


